general:
  gitSshKeyCredentialsId: 'SSH_github'
  scanType: 'npm'
  verbose: true
  whitesourceProductName: 'SHC - SAP RECAST CONVERSAT OD 2.0 2012'
  whitesourceProductToken: '15baf1e85c3d48e29402c00255f1e4afee49083d3e76495c91278719ee935cfb'
  whitesourceUserTokenCredentialsId: 'Whitesource_UserKey'
steps:
  setVersion:
    buildTool: 'npm'
    commitVersion: true
    tagPrefix: ''
  executeBuild:
    xMakeShipmentType: 'indirectshipment'
  executeCheckmarxScan:
    checkmarxCredentialsId: 'CheckmarxUser'
    checkmarxGroupId: '110ebc45-3f3b-45c4-a2d0-781ab3050045'
    checkmarxProject: 'ML-CAI-webchat'
    preset: '100154'
  executeWhitesourceScan:
    securityVulnerabilities: true
  executePPMSComplianceCheck:
    ppmsCredentialsId: 'PPMSCompliance'
    ppmsID: '73555000100200012242'
    ppmsChangeRequestUpload: true
  writeInflux:
    influxServer: 'jenkins'
    wrapInNode: true
  sendNotificationMail:
    wrapInNode: true
