general:
  gitSshKeyCredentialsId: 'SSH_github'
  scanType: 'npm'
  verbose: true
  whitesourceProductName: 'SHC - SAP CONVERSATIONAL AI PAL'
  whitesourceProductToken: '2cb973cbfa874f47b07a0adc60e0cee431c14992f6484b90a2b6d0073e8ef695'
  whitesourceUserTokenCredentialsId: 'Whitesource_UserKey'
steps:
  setVersion:
    buildTool: 'npm'
    commitVersion: true
    tagPrefix: ''
  executeBuild:
    xMakeShipmentType: 'indirectshipment'
  executeCheckmarxScan:
    checkmarxCredentialsId: 'CheckmarxUser'
    checkmarxGroupId: '110ebc45-3f3b-45c4-a2d0-781ab3050045'
    checkmarxProject: 'ML-CAI-webchat'
    preset: '100154'
  executeWhitesourceScan:
    securityVulnerabilities: true
  executePPMSComplianceCheck:
    ppmsCredentialsId: 'PPMSCompliance'
    ppmsID: '73555000100200012242'
    ppmsChangeRequestUpload: true
  writeInflux:
    influxServer: 'jenkins'
    wrapInNode: true
  sendNotificationMail:
    wrapInNode: true
